### ISSUE TITLE
Certain blocks break symbol lookup

### ISSUE THREAD

**Issue by andersodt** [MiguelSavignano/vs-code-ruby-symbols#1]
Using Rails, in my models/*.rb files, if I have any loop blocks, scope blocks, or callback blocks, I cannot get any symbols to show up. If I remove these blocks, it works as expected.

Some examples:

```
before_validation(on: :create) do
   ...
end

after_initialize do
  ...
end

loop do
  ...
end

scope :within, ->(time) do
  where('created_at >= ?', time.ago)
end
```

**Comment by MiguelSavignano** [comment]
Thanks for create this issue, it's fixed in version 0.1.5

The blocks before_validation,  after_initialize, loop, and scope these aren't Will be shown as a symbol.
