### ISSUE TITLE
`var = begin` causes symbols to go away

### ISSUE THREAD

**Issue by jacquescrocker** [MiguelSavignano/vs-code-ruby-symbols#3]
If I have a block in my ruby file:

```
result = begin
  something_something
  something_else
end
result.save

````

All the ruby symbols in the file go away

![screen shot 2018-04-03 at 11 19 32 am](https://user-images.githubusercontent.com/206662/38267617-e5bea1e0-3730-11e8-8a84-4920be03e00e.png)

When I remove that block, the symbols come back

**Comment by MiguelSavignano** [comment]
@jacquescrocker try the new version 0.1.6

**Comment by jacquescrocker** [comment]
Works now, thanks Miguel!
